import {
  ButtonContainer,
  Header,
  ImageContainer,
  NavigationContainer,
  NavLink,
} from "@/styles/styles";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <ImageContainer>
          {" "}
          <Image
            width={200}
            height={60}
            alt="papillon logo"
            src="/../public/assets/papillon.png"
            style={{ borderRadius: 10 }}
          />
        </ImageContainer>
      </Header>
      <NavigationContainer>
        <ButtonContainer></ButtonContainer>
        <ButtonContainer>
          {" "}
          <NavLink href="#">Home</NavLink>
        </ButtonContainer>
      </NavigationContainer>
    </>
  );
}
